---
- name: ensure required packages are installed for Java 7
  apt: name=$item state=latest update_cache=yes
  with_items:
    - python-software-properties

- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java'

- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Update APT package cache
  action: apt update_cache=yes

- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes

- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes
  
- name: Apache Storm | Make sure the storm group is present
  action: group gid={{ storm_gid }} name={{ storm_group }} state=present

- name: Apache Storm | Make sure the storm user directory is present
  action: file path="/app/home/{{ storm_user }}" state=directory

- name: Apache Storm | Make sure the storm user is present
  user: uid={{ storm_uid }} name={{ storm_user }} group={{ storm_group }} home="/app/home/{{ storm_user }}" shell=/bin/bash state=present comment="Storm user"

- name: Apache Storm | Set the right storm user directory permissions
  action: file path="/app/home/{{ storm_user }}" owner={{ storm_user }} group={{ storm_group }} mode=0700 state=directory

- name: Apache Storm | Set the right expiration on the storm user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{ storm_user }}"
  changed_when: False
  
- name: Apache Storm | Download the storm source tar.gz in /tmp if not yet present
  command: wget {{apache_mirror}}/{{ storm_version }}/{{ storm_version }}.tar.gz chdir=/tmp creates=/tmp/{{ storm_version }}.tar.gz

- name: Apache Storm | Untar the storm source in /usr/local/etc
  shell: tar -zxvf /tmp/{{ storm_version }}.tar.gz chdir=/usr/local/etc creates=/usr/local/etc/{{ storm_version }}

- name: Apache Storm | Update the storm install permissions
  file: path=/usr/local/etc/{{ storm_version }} owner={{ storm_user }} group={{ storm_group }} state=directory recurse=yes

- name: Apache Storm | Update the symbolic link to the storm install
  file: path=/usr/local/etc/storm src=/usr/local/etc/{{ storm_version }} state=link force=yes

- name: Apache Storm | Make sure the local working directory for storm is present
  file: path={{ storm_local_dir }} owner={{ storm_user }} group={{ storm_group }} mode=0750 state=directory

- name: Apache Storm | Update configuration
  template: src=storm.yaml.j2 dest=/usr/local/etc/storm/conf/storm.yaml owner={{ storm_user }} group={{ storm_group }} mode=0644
