---

- name: Get ES RPM
  get_url: url="{{ es_url }}" dest=/tmp/elasticsearch-{{ es_version }}.noarch.rpm
  tags:
    - elasticsearch
    - system
    - build  

- name: Install ES
  command: rpm -i /tmp/elasticsearch-{{ es_version }}.noarch.rpm
  tags:
    - elasticsearch
    - system
    - build

- name: Stop ES and disable in boot
  service: name=elasticsearch state=stopped enabled=no
  tags:
    - elasticsearch
    - system
    - build

- name: Install EC2 esPluginEC2
  command: bin/plugin -install elasticsearch/elasticsearch-cloud-aws/{{ ec2_version }} chdir=/usr/share/elasticsearch
  tags:
    - elasticsearch
    - system
    - build

- name: Install Head plugin
  command: bin/plugin -install elasticsearch/marvel/latest chdir=/usr/share/elasticsearch
  tags:
    - elasticsearch
    - system
    - build

- name: Install Marvel plugin
  command: bin/plugin -install mobz/elasticsearch-head chdir=/usr/share/elasticsearch
  tags:
    - elasticsearch
    - system
    - build

- name: Install ICU plugin
  command: bin/plugin -install elasticsearch/elasticsearch-analysis-icu/{{ icu_version }} chdir=/usr/share/elasticsearch
  tags:
    - elasticsearch
    - system
    - build  

- name: Configure elasticsearch
  template: src=etc/elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  tags:
    - elasticsearch
    - system
    - build

- name: Configure Security limits soft
  lineinfile: dest=/etc/security/limits.conf line='elasticsearch soft nofile 65535' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - elasticsearch
    - system
    - build

- name: Configure Security limits hard 
  lineinfile: dest=/etc/security/limits.conf line='elasticsearch hard nofile 65535' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - elasticsearch
    - system
    - build

- name: Configure Security limits memlock
  lineinfile: dest=/etc/security/limits.conf line='elasticsearch - memlock unlimited' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - elasticsearch
    - system
    - build

- name: Configure Security limits root memlock
  lineinfile: dest=/etc/security/limits.conf line='root - memlock unlimited' regexp='^#\ End\ of\ file(.*)' insertafter='^# End of file' state=present
  tags:
    - elasticsearch
    - system
    - build  

- name: sysconfig elasticsearch
  template: src=etc/sysconfig/elasticsearch dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644
  tags:
    - elasticsearch
    - system
    - build 

- name: unlimited in init.d
  lineinfile: dest=/etc/security/limits.conf line='su $ES_USER --shell /bin/bash -c "ulimit -l unlimited"' regexp='^(.*)daemon\ --user(.*)' insertbefore='^(.*)daemon --user' state=present
  tags:
    - elasticsearch
    - system
    - build

- name: Configure MEMLOCK usr/lib
  lineinfile: dest=/usr/lib/systemd/system/elasticsearch.service line='LimitMEMLOCK=infinity' regexp='^#LimitMEMLOCK=infinity(.*)' state=present
  tags:
    - elasticsearch
    - system
    - build

#- name: sysctl
#  lineinfile: dest=/etc/sysctl.conf line='vm.max_map_count=262144' state=present
#  tags:
#  - elasticsearch
#  - system
#  - build

- name: Config on boot
  template: src=etc/reuters/instance_conf.d/10_elastic_search dest=/etc/reuters/instance_conf.d/10_elastic_search owner=root group=root mode=0644
  tags:
    - elasticsearch
    - system
    - build